# NOTE: this version derived from https://github.com/rust-lang/rust/blob/master/rustfmt.toml
version = "Two"
#use_small_heuristics = "Max"
#merge_derives = false

ignore = [
    "/docs/",
    "/target/",
]