[workspace]
resolver = "2"
members = [
    "common",
    "compiler",
    "runtime/lib",
    "runtime/flavors/*",
    "macros",
    "orchestrator",
]
exclude = ["runtime/shim", "samples/crates/", "scripts"]

[workspace.dependencies]
# Unless we specify the package, it won't be renamed.
common = { path = "common", package = "common" }
macros = { path = "macros" }
runtime_basic_li = { path = "runtime/flavors/basic_li" }
runtime_noop = { path = "runtime/flavors/noop" }

config = "0.14.1"
const_format = "0.2.33"
delegate = "0.13.1"
derive_more = { version = "1.0.0", features = ["full"] }
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
serde = { version = "1.0.215", features = ["derive"] }
