[workspace]
resolver = "2"
members = [
    "common",
    "compiler",
    "runtime/lib",
    "runtime/flavors/*",
    "macros",
]
exclude = [
    "runtime/shim",
    "samples/crates/",
    "scripts",
]
