[workspace]
resolver = "2"
members = [
    "common",
    "compiler",
    "runtime/lib",
    "runtime/flavors/*",
    # We keep the shim in the workspace for project management, although it is built with the compiler.
    "runtime/shim",
    "macros",
]
exclude = [
    "samples/crates/"
]
