[workspace]
resolver = "2"
members = [
    "common",
    "compiler",
    "runtime",
    # We keep the shim project here to make the project management easier.
    "runtime_shim",
    "macros",
    "runtime_basic",
    "runtime_noop",
]
exclude = [
    "samples/crates/"
]
