[call]
# panic, concretization, over_approximation, optimistic_concretization
external_call = "concretization"

[sym_place]
# proj_expression, concretization, stamping
read = "stamping"
write = "stamping"

[[outputs]]
type = "file"
directory = "output"
format = "binary"
