codegen_all_mir = true
marker_cfg_name = "leafc"
override_sysroot = true

[runtime_shim]
[runtime_shim.location.external]
crate_name = "leaf"
search_path = "sysroot"

[internalization_rules]
exclude = ["LLVMFuzzerInitialize"]
