[workspace]
resolver = "2"
members = ["basic_pro_conc", "basic_pro_conc/fuzz"]

[workspace.dependencies]
libfuzzer-sys = { version = "0.14.1", package = "libafl_libfuzzer", path = "../libfuzzer" }

[workspace.lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(leafc)'] }
