[build]
rustflags = [
    "--cfg",
    "runtime_access=\"safe_brt\"",
    "--cfg",
    "place_addr",
    "--cfg",
    "abs_concrete",
    # "--cfg",
    # "nctfe",
    # "--cfg",
    # "runtime_impl=\"noop\"",
]

[env]
# You can set this (during compile time) to change the name of the runtime library
# in the extern prelude of the compiled program.
