[build]
rustflags = [
    "--cfg",
    "runtime_access=\"safe_brt\"",
    # "--cfg",
    # "place_addr",
    # "--cfg",
    # "abs_concrete",
    "--cfg",
    "external_call=\"optim_conc\"", # Possible values: concretize, overapprox, optim_conc, panic
]
