[build]
rustflags = [
    "--cfg",
    "runtime_access=\"safe_brt\"",
    "--cfg",
    "place_addr",
    "--cfg",
    "abs_concrete",
    "--cfg",
    "types_db_fmt=\"rkyv\""
]

[env]
# You can set this (during compile time) to change the name of the runtime library
# in the extern prelude of the compiled program.
