[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.17"
env_logger = "0.10.0"
runtime = { path = "../runtime", version = "0.1.0" }
delegate = "0.10.0"

[package.metadata.rust-analyzer]
rustc_private = true