[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "leafc"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common", features = ["tyexp"] }
macros = { path = "../macros" }

log = "0.4.17"
env_logger = "0.10.0"
delegate = "0.12.0"
paste = "1.0"
bimap = "0.6.3"
derive_more = "0.99.11"
const_format = "0.2.32"
glob = "0.3.1"

[package.metadata.rust-analyzer]
rustc_private = true
