[package]
name = "common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
std = []
logging = ["dep:tracing"]
tyexp = ["std", "dep:serde", "dep:serde_json", "logging"]
config = ["dep:config", "logging"]

[dependencies]
# No dependencies are supposed to be used by this crate in the mode that is used by the shim library.

serde = { version = "1.0.188", features = ["derive"], optional = true }
serde_json = { version = "1.0.107", optional = true }
log = { version = "0.4.20", optional = true }
config = { version = "0.14.0", optional = true }
tracing = {version="0.1", optional = true}
