[package]
name = "with_dep"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# This dependency is supposed to not be used by the runtime library.
[dependencies]
bitflags = "2.4.1"