name: Test

on:
  push:
    branches: [main]
  pull_request: # Every target branch

env:
  RUST_LOG: error

jobs:
  rust-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v2

      - name: Prerequisite - Souffle
        run: |
          # Define the version you want to install
          SOUFFLE_VERSION="2.5"  # Change this to the desired version
          wget "https://github.com/souffle-lang/souffle/releases/download/${SOUFFLE_VERSION}/x86_64-ubuntu-2404-souffle-${SOUFFLE_VERSION}-Linux.deb"
          sudo apt-get update
          sudo dpkg -i "x86_64-ubuntu-2404-souffle-${SOUFFLE_VERSION}-Linux.deb" || sudo apt-get install -f

      - name: Build
        run: cargo build --verbose

      - name: Add no-op runtime to path
        run: |
          mkdir -p libleafrt_dir
          ln -s target/debug/libleafrt_noop.so libleafrt_dir/libleafrt_noop.so
        env:
          LD_LIBRARY_PATH: $PWD/libleafrt_dir:$LD_LIBRARY_PATH     

      - name: Run tests
        run: cargo test --verbose
