name: Test

on:
  push:
    branches: [main]
  pull_request: # Every target branch

env:
  RUST_LOG: debug

jobs:
  rust-test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          target: x86_64-unknown-linux-gnu
      - name: Install Rust development components
        run: rustup component add rust-src rustc-dev llvm-tools-preview
      - name: Build
        run: cargo build
      - name: Run tests
        run: cargo test --verbose
